### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by retrfy** [iqiyi/Lens#2]
--------- beginning of crash
08-16 10:54:37.515 19972 24119 E AndroidRuntime: FATAL EXCEPTION: Thread-36
08-16 10:54:37.515 19972 24119 E AndroidRuntime: Process: com.qiyi.video:plugin1, PID: 19972
08-16 10:54:37.515 19972 24119 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.view.ViewGroup.getLayoutParams()' on a null object reference
08-16 10:54:37.515 19972 24119 E AndroidRuntime: at com.qiyi.lens.ui.FloatingPanel$2.onEnd(FloatingPanel.java:175)
08-16 10:54:37.515 19972 24119 E AndroidRuntime: at com.qiyi.lens.ui.widget.FrameAnimation$2.onAnimationEnd(FrameAnimation.java:52)
08-16 10:54:37.515 19972 24119 E AndroidRuntime: at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:552)
08-16 10:54:37.515 19972 24119 E AndroidRuntime: at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1250)
08-16 10:54:37.515 19972 24119 E AndroidRuntime: at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1492)
08-16 10:54:37.515 19972 24119 E AndroidRuntime: at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
08-16 10:54:37.515 19972 24119 E AndroidRuntime: at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
08-16 10:54:37.515 19972 24119 E AndroidRuntime: at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
08-16 10:54:37.515 19972 24119 E AndroidRuntime: at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1098)
08-16 10:54:37.515 19972 24119 E AndroidRuntime: at android.view.Choreographer.doCallbacks(Choreographer.java:895)
08-16 10:54:37.515 19972 24119 E AndroidRuntime: at android.view.Choreographer.doFrame(Choreographer.java:823)
08-16 10:54:37.515 19972 24119 E AndroidRuntime: at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1086)
08-16 10:54:37.515 19972 24119 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:873)
08-16 10:54:37.515 19972 24119 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:99)
08-16 10:54:37.515 19972 24119 E AndroidRuntime: at android.os.Looper.loop(Looper.java:201)
08-16 10:54:37.515 19972 24119 E AndroidRuntime: at com.qiyi.lens.ui.exceptionPanel.CrashInterceptor$1.run(CrashInterceptor.java:88)
08-16 10:54:37.515 19972 24119 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:873)
08-16 10:54:37.515 19972 24119 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:99)
08-16 10:54:37.515 19972 24119 E AndroidRuntime: at android.os.Looper.loop(Looper.java:201)
08-16 10:54:37.515 19972 24119 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6861)
08-16 10:54:37.515 19972 24119 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
08-16 10:54:37.515 19972 24119 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
08-16 10:54:37.515 19972 24119 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by Carlyle-Lee** [comment]
hi, pls update for the latest version . 1.2.4. this bug has been resolved.

**Comment by Carlyle-Lee** [comment]
Thanks for your feedback
